package svp.jna;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : ssp16.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("svp")
public class cart_hw_t extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * cart_hw_t hw;           /* cartridge internal hardware * /<br>
	 * ROM area<br>
	 * C type : unsigned char[0x300000]
	 */
	@Array({0x300000})
	@Field(0)
	public Pointer<Byte > rom() {
		return this.io.getPointerField(this, 0);
	}
	public cart_hw_t() {
		super();
	}
	public cart_hw_t(Pointer pointer) {
		super(pointer);
	}
}
