package svp.jna;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;

/**
 * <i>native declaration : ssp16.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("svp")
public class ssp1601_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : mem_union */
	@Field(0)
	public mem_union mem() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : mem_union */
	@Field(0)
	public ssp1601_t mem(mem_union mem) {
		this.io.setNativeObjectField(this, 0, mem);
		return this;
	}
	/**
	 * general registers<br>
	 * C type : ssp_reg_t[16]
	 */
	@Array({16})
	@Field(1)
	public Pointer<ssp_reg_t > gr() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : ptr_union */
	@Field(2)
	public ptr_union ptr() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : ptr_union */
	@Field(2)
	public ssp1601_t ptr(ptr_union ptr) {
		this.io.setNativeObjectField(this, 2, ptr);
		return this;
	}
	/** C type : unsigned short[6] */
	@Array({6})
	@Field(3)
	public Pointer<Short > stack() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * read/write modes/addrs for PM0-PM5<br>
	 * C type : unsigned int[2][6]
	 */
	@Array({2, 6})
	@Field(4)
	public Pointer<Integer > pmac() {
		return this.io.getPointerField(this, 4);
	}
	@Field(5)
	public int emu_status() {
		return this.io.getIntField(this, 5);
	}
	@Field(5)
	public ssp1601_t emu_status(int emu_status) {
		this.io.setIntField(this, 5, emu_status);
		return this;
	}
	/** C type : unsigned int[30] */
	@Array({30})
	@Field(6)
	public Pointer<Integer > pad() {
		return this.io.getPointerField(this, 6);
	}
	/** <i>native declaration : ssp16.h:52</i> */
	@Union
	public static class mem_union extends StructObject {
		static {
			BridJ.register();
		}
		/**
		 * 2 internal RAM banks<br>
		 * C type : unsigned short[256 * 2]
		 */
		@Array({256 * 2})
		@Field(0)
		public Pointer<Short > RAM() {
			return this.io.getPointerField(this, 0);
		}
		/** C type : bank_struct */
		@Field(1)
		public bank_struct bank() {
			return this.io.getNativeObjectField(this, 1);
		}
		/** C type : bank_struct */
		@Field(1)
		public mem_union bank(bank_struct bank) {
			this.io.setNativeObjectField(this, 1, bank);
			return this;
		}
		/** <i>native declaration : ssp16.h:54</i> */
		public static class bank_struct extends StructObject {
			static {
				BridJ.register();
			}
			/** C type : unsigned short[256] */
			@Array({256})
			@Field(0)
			public Pointer<Short > RAM0() {
				return this.io.getPointerField(this, 0);
			}
			/** C type : unsigned short[256] */
			@Array({256})
			@Field(1)
			public Pointer<Short > RAM1() {
				return this.io.getPointerField(this, 1);
			}
			public bank_struct() {
				super();
			}
			public bank_struct(Pointer pointer) {
				super(pointer);
			}
		};
		public mem_union() {
			super();
		}
		public mem_union(Pointer pointer) {
			super(pointer);
		}
	};
	/** <i>native declaration : ssp16.h:60</i> */
	@Union
	public static class ptr_union extends StructObject {
		static {
			BridJ.register();
		}
		/**
		 * BANK pointers<br>
		 * C type : unsigned char[8]
		 */
		@Array({8})
		@Field(0)
		public Pointer<Byte > r() {
			return this.io.getPointerField(this, 0);
		}
		/** C type : bank_struct */
		@Field(1)
		public mem_union.bank_struct bank() {
			return this.io.getNativeObjectField(this, 1);
		}
		/** C type : bank_struct */
		@Field(1)
		public ptr_union bank(mem_union.bank_struct bank) {
			this.io.setNativeObjectField(this, 1, bank);
			return this;
		}
		/** <i>native declaration : ssp16.h:62</i> */
		public static class bank_struct extends StructObject {
			static {
				BridJ.register();
			}
			/** C type : unsigned char[4] */
			@Array({4})
			@Field(0)
			public Pointer<Byte > r0() {
				return this.io.getPointerField(this, 0);
			}
			/** C type : unsigned char[4] */
			@Array({4})
			@Field(1)
			public Pointer<Byte > r1() {
				return this.io.getPointerField(this, 1);
			}
			public bank_struct() {
				super();
			}
			public bank_struct(Pointer pointer) {
				super(pointer);
			}
		};
		public ptr_union() {
			super();
		}
		public ptr_union(Pointer pointer) {
			super(pointer);
		}
	};
	public ssp1601_t() {
		super();
	}
	public ssp1601_t(Pointer pointer) {
		super(pointer);
	}
}
