package svp.jna;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;

/**
 * <i>native declaration : ssp16.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union
@Library("svp")
public class ssp_reg_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0)
	public int v() {
		return this.io.getIntField(this, 0);
	}
	@Field(0)
	public ssp_reg_t v(int v) {
		this.io.setIntField(this, 0, v);
		return this;
	}
	/** C type : byte_struct */
	@Field(1)
	public byte_struct byte$() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : byte_struct */
	@Field(1)
	public ssp_reg_t byte$(byte_struct byte$) {
		this.io.setNativeObjectField(this, 1, byte$);
		return this;
	}
	/** <i>native declaration : ssp16.h:39</i> */
	public static class byte_struct extends StructObject {
		static {
			BridJ.register();
		}
		/** #ifdef LSB_FIRST */
		@Field(0)
		public short l() {
			return this.io.getShortField(this, 0);
		}
		/** #ifdef LSB_FIRST */
		@Field(0)
		public byte_struct l(short l) {
			this.io.setShortField(this, 0, l);
			return this;
		}
		@Field(1)
		public short h() {
			return this.io.getShortField(this, 1);
		}
		@Field(1)
		public byte_struct h(short h) {
			this.io.setShortField(this, 1, h);
			return this;
		}
		public byte_struct() {
			super();
		}
		public byte_struct(Pointer pointer) {
			super(pointer);
		}
	};
	public ssp_reg_t() {
		super();
	}
	public ssp_reg_t(Pointer pointer) {
		super(pointer);
	}
}
