package svp.jna;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * <i>native declaration : svp.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("svp")
public class svp_t extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * IRAM (0-0x7ff) and program ROM (0x800-0x1ffff)<br>
	 * C type : unsigned char[0x20000]
	 */
	@Array({0x20000})
	@Field(0)
	public Pointer<Byte > iram_rom() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : unsigned char[0x20000] */
	@Array({0x20000})
	@Field(1)
	public Pointer<Byte > dram() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : ssp1601_t */
	@Field(2)
	public ssp1601_t ssp1601() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : ssp1601_t */
	@Field(2)
	public svp_t ssp1601(ssp1601_t ssp1601) {
		this.io.setNativeObjectField(this, 2, ssp1601);
		return this;
	}
	public svp_t() {
		super();
	}
	public svp_t(Pointer pointer) {
		super(pointer);
	}
}
