package m68k.jsontest;


import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import m68k.jsontest.schema.FinalState;

import java.util.List;

/**
 * Autogenerated by:
 * https://www.jsonschema2pojo.org/
 */
public class InstData {

    @SerializedName("name")
    @Expose
    public String name;
    @SerializedName("initial state")
    @Expose
    public InitialState initialState;
    @SerializedName("final state")
    @Expose
    public FinalState finalState;
    @SerializedName("initial memory")
    @Expose
    public List<Integer> initialMemory = null;
    @SerializedName("final memory")
    @Expose
    public List<Integer> finalMemory = null;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public InitialState getInitialState() {
        return initialState;
    }

    public void setInitialState(InitialState initialState) {
        this.initialState = initialState;
    }

    public FinalState getFinalState() {
        return finalState;
    }

    public void setFinalState(FinalState finalState) {
        this.finalState = finalState;
    }

    public List<Integer> getInitialMemory() {
        return initialMemory;
    }

    public void setInitialMemory(List<Integer> initialMemory) {
        this.initialMemory = initialMemory;
    }

    public List<Integer> getFinalMemory() {
        return finalMemory;
    }

    public void setFinalMemory(List<Integer> finalMemory) {
        this.finalMemory = finalMemory;
    }
}

